package dev.squire.server.tool.builtin;

import dev.squire.common.errors.ErrorCode;
import dev.squire.common.errors.ErrorPayload;
import dev.squire.common.protocol.ToolResult;
import dev.squire.server.runtime.SquireRuntime;
import dev.squire.server.tool.AgentPermission;
import dev.squire.server.tool.ArgDefinition;
import dev.squire.server.tool.RiskLevel;
import dev.squire.server.tool.ToolDefinition;
import dev.squire.server.tool.ToolExposure;
import dev.squire.server.tool.ToolRegistry;

/**
 * 职业成长线解锁的那些工具（设计文档 §23）。
 *
 * <h2>为什么单独一个文件</h2>
 * <p>{@code BuiltinTools} 里的每一条都是「所有随从都会」的通用词汇。这里的每一条
 * 反过来：<b>只有走到那一级的随从才看得见</b>。混在一起的话，「这个工具谁能用」
 * 就得逐条去读注册代码，而门槛表在另一个文件里——两边迟早对不上。</p>
 *
 * <h2>每一条都接到已经存在的实现上</h2>
 * <p>没有一条在这里重新实现逻辑。它们全部转交给 {@code SquireRuntime} 上那几个
 * <b>面板按钮和命令已经在用</b>的方法，那些方法各自带着等级闸和参数夹取。
 * 所以模型走的路和玩家点按钮走的是同一条——不存在「命令能做但面板不能」的分叉，
 * 也不会因为多了一个调用方就多出一套校验。</p>
 *
 * <h2>不为凑数造工具</h2>
 * <p>守卫的威胁判断、拦截、守护协议是<b>自动行为</b>，玩家从来不会去「调用」，
 * 所以它们在这里一条工具都没有。能力和工具是 0/1/多的关系，不是一一对应。</p>
 */
public final class ProfessionTools {

	private ProfessionTools() {
	}

	public static void register(ToolRegistry registry) {
		registerGuard(registry);
		registerEngineer(registry);
	}

	/** 拿到运行时；最小/测试运行时可能没有。 */
	private static SquireRuntime runtime() {
		return SquireRuntime.get();
	}

	/**
	 * 把一次玩家意图的执行结果转成工具结果。
	 *
	 * <p>失败一律带上服务端给玩家的<b>那句话</b>——模型据此可以如实转述
	 * 「他还不会这个，要练到 Lv.5」，而不是自己编一个理由。</p>
	 */
	private static ToolResult report(dev.squire.common.protocol.ToolCall call,
			java.util.function.Function<net.minecraft.server.network.ServerPlayerEntity,
				SquireRuntime.ExecutionResult> action,
			dev.squire.server.tool.ToolExecutionContext ctx) {
		SquireRuntime runtime = runtime();
		if (runtime == null) {
			return ToolResult.failed(call.callId(),
				ErrorPayload.of(ErrorCode.INTERNAL_ERROR, "runtime unavailable"));
		}
		var player = runtime.requesterOf(ctx.requesterId());
		if (player == null) {
			return ToolResult.failed(call.callId(),
				ErrorPayload.of(ErrorCode.PERMISSION_DENIED, "requester offline"));
		}
		SquireRuntime.ExecutionResult result = action.apply(player);
		return result.success()
			? ToolResult.success(call.callId(),
				java.util.Map.of("message", result.message()))
			: ToolResult.failed(call.callId(),
				ErrorPayload.of(ErrorCode.PRECONDITION_FAILED, result.message()));
	}

	// ------------------------------------------------------------------ 守卫

	private static void registerGuard(ToolRegistry registry) {
		// Lv.5 补给意识。玩家问「你还有多少箭」时，这是唯一能如实回答的路。
		registry.register(ToolDefinition.builder("combat.supplies")
			.description("Report what the squire is carrying for a fight: food, healing "
				+ "potions, arrows, spare weapons, bow and shield. Read-only.")
			.permission(AgentPermission.QUERY)
			.risk(RiskLevel.LOW)
			.exposure(ToolExposure.MODEL_PUBLIC)
			.build(), (call, ctx) -> report(call, player -> runtime().supplyReport(player), ctx));

		// Lv.8 战斗姿态。
		registry.register(ToolDefinition.builder("combat.set_stance")
			.description("Set how aggressively the squire fights: defensive (short "
				+ "chase, stays close), balanced (default), aggressive (long chase). "
				+ "Changes behaviour only - never damage numbers.")
			.arg(ArgDefinition.required("stance", ArgDefinition.ArgType.STRING,
				"one of: defensive, balanced, aggressive"))
			.permission(AgentPermission.COMBAT)
			.risk(RiskLevel.LOW)
			.exposure(ToolExposure.MODEL_PUBLIC)
			.build(), (call, ctx) -> report(call,
				player -> runtime().setCombatStance(player,
					String.valueOf(call.arguments().get("stance"))), ctx));
	}

	// ------------------------------------------------------------------ 工程师

	private static void registerEngineer(ToolRegistry registry) {
		// Lv.1 参数化蓝图的入口。注意 blueprint.place（按现成蓝图施工）是所有随从
		// 都有的，不在这条成长线上——这里解锁的是「按参数生成一份新蓝图」。
		registry.register(ToolDefinition.builder("blueprint.design")
			.description("Start a parametric building site from a template and show the "
				+ "particle preview. The player then adjusts and confirms; nothing is "
				+ "placed until they do. Shapes are generated by the server, never by you.")
			.arg(ArgDefinition.required("template", ArgDefinition.ArgType.STRING,
				"template id, e.g. shed / small_house / house / large_house / "
					+ "warehouse / watchtower / outpost"))
			.permission(AgentPermission.WORLD_PLACE)
			.risk(RiskLevel.LOW)
			.exposure(ToolExposure.MODEL_PUBLIC)
			.build(), (call, ctx) -> report(call,
				player -> runtime().design(player,
					String.valueOf(call.arguments().get("template"))), ctx));

		// Lv.2 尺寸。
		registry.register(ToolDefinition.builder("blueprint.set_size")
			.description("Resize the current site's footprint. Values are clamped to "
				+ "what this squire's level allows.")
			.arg(ArgDefinition.intRange("width", 5, 48, "footprint width"))
			.arg(ArgDefinition.intRange("depth", 5, 48, "footprint depth"))
			.permission(AgentPermission.WORLD_PLACE)
			.risk(RiskLevel.LOW)
			.exposure(ToolExposure.MODEL_PUBLIC)
			.build(), (call, ctx) -> report(call,
				player -> runtime().designSize(player,
					intArg(call, "width"), intArg(call, "depth")), ctx));

		// Lv.3 旋转。
		registry.register(ToolDefinition.builder("blueprint.rotate")
			.description("Rotate the current building site 90 degrees clockwise.")
			.permission(AgentPermission.WORLD_PLACE)
			.risk(RiskLevel.LOW)
			.exposure(ToolExposure.MODEL_PUBLIC)
			.build(), (call, ctx) -> report(call, player -> runtime().blueprintRotate(player), ctx));

		// Lv.4 材料分区。
		registry.register(ToolDefinition.builder("blueprint.set_material_region")
			.description("Change the material of one structural region of the current "
				+ "site (foundation / wall / floor / roof / window / trim) instead of "
				+ "the whole building.")
			.arg(ArgDefinition.intRange("slot", 0, 5,
				"region index: 0 foundation, 1 wall, 2 floor, 3 roof, 4 window, 5 trim"))
			.permission(AgentPermission.WORLD_PLACE)
			.risk(RiskLevel.LOW)
			.exposure(ToolExposure.MODEL_PUBLIC)
			.build(), (call, ctx) -> report(call,
				player -> runtime().blueprintCycleMaterial(player,
					intArg(call, "slot"), 1), ctx));

		// Lv.5 结构变体：一条能力开出四个工具。
		registry.register(ToolDefinition.builder("blueprint.set_variant")
			.description("Pick a predefined structural variant for the current site.")
			.arg(ArgDefinition.required("kind", ArgDefinition.ArgType.STRING,
				"one of: roof, foundation, window, entrance"))
			.arg(ArgDefinition.required("value", ArgDefinition.ArgType.STRING,
				"roof: flat/gable/hip; foundation: none/stone/raised; "
					+ "window: small/wide/tall; entrance: center/side"))
			.permission(AgentPermission.WORLD_PLACE)
			.risk(RiskLevel.LOW)
			.exposure(ToolExposure.MODEL_PUBLIC)
			.build(), (call, ctx) -> report(call, player -> {
				String kind = String.valueOf(call.arguments().get("kind"));
				String value = String.valueOf(call.arguments().get("value"));
				return switch (kind.toLowerCase(java.util.Locale.ROOT)) {
					case "roof" -> runtime().designRoof(player, value);
					case "foundation" -> runtime().designFoundation(player, value);
					case "window" -> runtime().designWindow(player, value);
					case "entrance" -> runtime().designEntrance(player, value);
					default -> SquireRuntime.ExecutionResult.refused(
						"[Squire] 变体种类只有 roof / foundation / window / entrance。");
				};
			}, ctx));

		// Lv.6 多层。
		registry.register(ToolDefinition.builder("blueprint.set_floors")
			.description("Set how many storeys the current site has (1-3). Floors and "
				+ "stairs are generated by the server.")
			.arg(ArgDefinition.intRange("floors", 1, 3, "storey count"))
			.permission(AgentPermission.WORLD_PLACE)
			.risk(RiskLevel.LOW)
			.exposure(ToolExposure.MODEL_PUBLIC)
			.build(), (call, ctx) -> report(call,
				player -> runtime().designFloors(player, intArg(call, "floors")), ctx));

		// Lv.7 镜像 + 附属模块。
		registry.register(ToolDefinition.builder("blueprint.mirror")
			.description("Mirror the current site along an axis.")
			.arg(ArgDefinition.required("axis", ArgDefinition.ArgType.STRING,
				"one of: x, z, xz, none"))
			.permission(AgentPermission.WORLD_PLACE)
			.risk(RiskLevel.LOW)
			.exposure(ToolExposure.MODEL_PUBLIC)
			.build(), (call, ctx) -> report(call,
				player -> runtime().designMirror(player,
					String.valueOf(call.arguments().get("axis"))), ctx));

		registry.register(ToolDefinition.builder("blueprint.add_module")
			.description("Attach or remove an optional module on the current site. "
				+ "Modules only connect at predefined points. Below Engineer Lv.8 only "
				+ "one module may be attached at a time.")
			.arg(ArgDefinition.required("module", ArgDefinition.ArgType.STRING,
				"one of: porch, chimney, storage_wing, tower, balcony"))
			.permission(AgentPermission.WORLD_PLACE)
			.risk(RiskLevel.LOW)
			.exposure(ToolExposure.MODEL_PUBLIC)
			.build(), (call, ctx) -> report(call,
				player -> runtime().designModule(player,
					String.valueOf(call.arguments().get("module"))), ctx));

		// Lv.9 预设库。
		registry.register(ToolDefinition.builder("blueprint.save_preset")
			.description("Save the current site's parameters under a name so the player "
				+ "can ask for the same building again later.")
			.arg(ArgDefinition.required("name", ArgDefinition.ArgType.STRING,
				"what the player calls this design"))
			.permission(AgentPermission.WORLD_PLACE)
			.risk(RiskLevel.LOW)
			.exposure(ToolExposure.MODEL_PUBLIC)
			.build(), (call, ctx) -> report(call,
				player -> runtime().designPresetSave(player,
					String.valueOf(call.arguments().get("name"))), ctx));

		registry.register(ToolDefinition.builder("blueprint.load_preset")
			.description("Open a preview of a design the player saved earlier.")
			.arg(ArgDefinition.required("name", ArgDefinition.ArgType.STRING,
				"the saved design's name"))
			.permission(AgentPermission.WORLD_PLACE)
			.risk(RiskLevel.LOW)
			.exposure(ToolExposure.MODEL_PUBLIC)
			.build(), (call, ctx) -> report(call,
				player -> runtime().designPresetLoad(player,
					String.valueOf(call.arguments().get("name"))), ctx));
	}

	private static int intArg(dev.squire.common.protocol.ToolCall call, String name) {
		Object raw = call.arguments().get(name);
		return raw instanceof Number number ? number.intValue() : 0;
	}
}
